stages:
  - build_pages

pages:
  stage: build_pages
  image: node:22-alpine
  cache:
    paths:
      - node_modules/
  before_script:
    - npm i -g corepack@latest && corepack enable
  script:
    - pnpm i
    - pnpm docs:gen
    - pnpm docs:build
    - pnpm build
    - pnpm build:demo
  artifacts:
    paths:
      - public
  variables:
    COREPACK_NPM_REGISTRY: https://mirrors.tencent.com/npm
  only:
    - main
